version: '2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: example
    
  web:
    build: .
    restart: always
    environment:
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
    command: sh ./migrations.sh 
    volumes:
  	  - path_to_logs_file_on_your_disk:/usr/src/boohub/myappBoohub/logs
    ports:
      - "8027:8000"
    depends_on:
      - db
