version: '2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: example
    
  web:
    build: .
    restart: always
    env_file: email.env
    command: sh ./migrations.sh 
    volumes:
      - .:/code
    ports:
      - "8027:8000"
    depends_on:
      - db
