version: '2'

services:
  db:
    image: postgres
    restart: always
    command: -p 8001
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: example
    
  web:
    build: .
    restart: always
    command: sh ./migrations.sh 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
