version: '2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: example
    
  web:
    build: .
    restart: always
    environment:
      - EMAIL_HOST_USER=djolepingvinboo@gmail.com
      - EMAIL_HOST_PASSWORD=pingvinDjoleRockyiZile22
    command: sh ./migrations.sh 
    volumes:
      - .:/code
    ports:
      - "8027:8000"
    depends_on:
      - db
