# Generated by Django 2.0.1 on 2018-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='emailAdresa',
            field=models.CharField(default='mail@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='korisnickoIme',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='lozinka',
            field=models.CharField(default='lozinka', max_length=50),
        ),
    ]
