# Generated by Django 2.0.1 on 2018-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20180129_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='emailAdresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='korisnickoIme',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='lozinka',
            field=models.CharField(max_length=50),
        ),
    ]
