sudo: required

language: python
python:
  - "3.5"  
 
services: 
  - docker

install:
  - pip install -r requirements.txt
  - pip install coverage
  
script:
  - docker-compose run web python3 manage.py test

before_install:
  - docker --version
  - cd ProjekatUKS/
  - docker build -t $DOCKER_USERNAME/uks_novi:proba .
  - docker images

after_success:
  - coverage report
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/uks_novi:proba
