sudo: required

language: python
python:
  - '3.5'
  
 
services: 
  - docker


install:
  - pip install -r requirements.txt
  
script:
  - python ProjekatUKS/github/tests.py
  


before_install:
  - docker --version
  - cd ProjekatUKS/
  - docker build -t $DOCKER_USERNAME/uks_novi:proba .
  - docker images

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/uks_novi:proba
