sudo: required

language: python
python:
  - "3.5"  
 
services: 
  - docker

before_install:
  - docker --version
  - cd ProjekatUKS/
  - docker build -t $DOCKER_USERNAME/uks_novi:proba .
  - docker images

install:
  - pip install -r requirements.txt

script:
  - docker-compose run web python3 manage.py makemigrations
  - docker-compose run web python3 manage.py migrate
  - docker-compose run web python3 manage.py test

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/uks_novi:proba
