sudo: required

notifications: # set notification options
  email:
    recipients:
      - cdjuric963@gmail.com
  on_success: always
  on_failure: always

language: python
python:
  - "3"
  
branches:
  only:
    - master  
#services: docker

# command to install dependencies
install:
  - pip install -r ProjekatUKS/requirements.txt
  
  
# command to run tests
script:
  - python tests.py
  


#script:
#  - docker build -t $DOCKER_USERNAME/mytravis:latest .
#  - docker images
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#- docker push $DOCKER_USERNAME/mytravis:latest
