sudo: required

notifications:
  email:
    recipients:
      - cdjuric963@gmail.com
  on_success: always
  on_failure: always

language: python
python:
  - "3.5"
  
branches:
  only:
    - master  
    
services: docker


install:
  - pip install -r ProjekatUKS/requirements.txt
  
  
script:
  - python ProjekatUKS/github/tests.py
  


script:
  - docker build -t $DOCKER_USERNAME/mytravis:latest .
  - docker images
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/mytravis:latest
