# Generated by Django 2.0 on 2018-02-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_remove_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(to='github.User'),
        ),
    ]
